### ISSUE TITLE
BCR-doc TODO

### ISSUE THREAD

**Issue by grst** [icbi-lab/scirpy#195]
- [ ]  Explain new terms in glossary more verbosely
 - [ ] update `receptor_model` page
 - [x] Review API doc for sonsistent term usage (IR instead of TCR...)
